# Generated by Django 4.2.5 on 2023-09-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=200, verbose_name='ЧПУ')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='превью')),
                ('created_date', models.DateTimeField(verbose_name='дата создания')),
                ('is_public', models.BooleanField(default=True, verbose_name='опубликовано или нет')),
                ('views_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('email', 'fio'),
            },
        ),
        migrations.CreateModel(
            name='ClientSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Установленный адресат',
                'verbose_name_plural': 'Установленные адресаты',
                'ordering': ('mailing',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='LogSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Последняя попытка')),
                ('status_post', models.CharField(verbose_name='Статус')),
                ('server_request', models.CharField(verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ('mailing',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_date', models.DateTimeField(verbose_name='дата создания')),
                ('end_date', models.DateTimeField(verbose_name='дата окончания')),
                ('intervals', models.CharField(choices=[('D', 'раз в день'), ('W', 'раз в неделю'), ('M', 'раз в месяц')], default='D', max_length=1, verbose_name='Периодичность')),
                ('status', models.PositiveSmallIntegerField(choices=[('E', 'включена'), ('D', 'отключена')], default='E', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('name',),
            },
        ),
    ]
